name: Build RekPatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: Download required files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir kpm
          cd kpm
          
          KernelPatch_LATEST_TAG=$(gh release list -R bmax121/KernelPatch --limit 1 | awk '{print $1}')
          if [ -z "$KernelPatch_LATEST_TAG" ]; then
            echo "Error: No release found for bmax121/KernelPatch"
            exit 1
          fi
          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/KernelPatch --pattern "kpimg-linux" || exit 1
          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/kernelPatch --pattern "kptools-android" || exit 1

          KPM_LATEST_TAG=$(gh release list -R lzghzr/APatch_kpm  --limit 1 | awk '{print $1}')
          if [ -z "$KPM_LATEST_TAG" ]; then
            echo "Error: No release found for lzghzr/APatch_kpm"
            exit 1
          fi
          gh release download "$KPM_LATEST_TAG" -R lzghzr/APatch_kpm --pattern "re_kernel*.kpm" || exit 1
          mv re_kernel_*_network.kpm Re-Kernel_network.kpm
          find . -type f -name "re_kernel_*.kpm" -exec mv {} Re-Kernel.kpm \;

          MAGISK_LATEST_TAG=$(gh release list -R topjohnwu/Magisk  --limit 1 | awk '{print $1}')
          if [ -z "$MAGISK_LATEST_TAG" ]; then
            echo "Error: No release found for topjohnwu/Magisk"
            exit 1
          fi
          gh release download "$MAGISK_LATEST_TAG" -R topjohnwu/Magisk --pattern "Magisk-*.apk" || exit 1



      - name: Repack ReKPatch
        run: |
          mkdir ReKPatch
          cp * ReKPatch

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: ReKPatch
          path: ReKPatch
