name: Build RekPatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: Download required files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir kpm
          cd kpm 
          echo "Fetching latest release for KernelPatch..."
          gh release download -R bmax121/KernelPatch --pattern "kpimg-linux"
          gh release download -R bmax121/kernelPatch --pattern "kptools-android"

          echo "Fetching latest release for APatch_kpm..."
          gh release download -R lzghzr/APatch_kpm --pattern "re_kernel*.kpm"
          mv re_kernel_*_network.kpm Re-Kernel_network.kpm
          find . -type f -name "re_kernel_*.kpm" -exec mv {} Re-Kernel.kpm \;
          
          cd ../
          echo "Fetching latest release for Magisk..."
          gh release download -R topjohnwu/Magisk --pattern "Magisk-*.apk"

          echo "Unpacking Magisk APK..."
          mkdir magisk_unpack
          unzip Magisk-*.apk -d magisk_unpack
          cp magisk_unpack/lib/arm64-v8a/libmagiskboot.so .
          rm -rf Magisk-*.apk magisk_unpack

      - name: Repack ReKPatch
        run: |
          mkdir ReKPatch
          for f in * .[^.]*; do
            [ "$f" != "ReKPatch" ] && mv "$f" ReKPatch/
          done

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: ReKPatch
          path: .
