name: Build RekPatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4

      - name: Download required files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cd kpm
          KernelPatch_LATEST_TAG=$(gh release list -R bmax121/KernelPatch --limit 1 | awk '{print $1}')
          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/KernelPatch --pattern "kpimg-linux"
          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/kernelPatch --pattern "kptools-android"

          KPM_LATEST_TAG=$(gh release list -R lzghzr/APatch_kpm  --limit 1 | awk '{print $1}')
          gh release download "$KPM_LATEST_TAG" -R lzghzr/APatch_kpm --pattern "re_kernel*.kpm"
          mv re_kernel_*_network.kpm Re-Kernel_network.kpm
          find . -type f -name "re_kernel_*.kpm" -exec mv {} Re-Kernel.kpm \;

          cd ../
          MAGISK_LATEST_TAG=$(gh release list -R topjohnwu/Magisk  --limit 1 | awk '{print $1}')
          gh release download "$MAGISK_LATEST_TAG" -R topjohnwu/Magisk --pattern "Magisk-*.apk"
          mkdir magisk_unpack
          unzip Magisk-*.apk -d magisk_unpack
          cp magisk_unpack/lib/arm64-v8a/libmagiskboot.so .
          rm -rf Magisk-*.apk magisk_unpack


      - name: Repack ReKPatch
        run: |
          mkdir ReKPatch
          cp * ReKPatch

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: ReKPatch
          path: ReKPatch
