name: Build RekPatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: clone repo
        run: git clone https://github.com/Prslc/ReKPatch.git

      - name: Download required files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          KernelPatch_LATEST_TAG=$(gh release list -R bmax121/KernelPatch --limit 1 | awk '{print $1}')
          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/KernelPatch --pattern "kpimg-android"
          gh release download "$KernelPatch_LATEST_TAG" -R bmax121/kernelPatch --pattern "kptools-android"

          KPM_LATEST_TAG=$(gh release list -R lzghzr/APatch_kpm  --limit 1 | awk '{print $1}')
          gh release download "$KPM_LATEST_TAG" -R lzghzr/APatch_kpm --pattern "re_kernel*.kpm"
          mv re_kernel_*_network.kpm Re-Kernel_network.kpm
          find . -type f -name "re_kernel_*.kpm" -exec mv {} Re-Kernel.kpm \;

      - name: Repack ReKPatch
        run: |
          mkdir -p ReKPatch/kpm
          cp kpimg-android kptools-android Re-Kernel.kpm Re-Kernel_network.kpm ReKPatch/kpm
          rm ReKPatch/.git ReKPatch/.github

      - name: Upload zip
        uses: actions/upload-artifact@v4
        with:
          name: ReKPatch
          path: ReKPatch
